version: "3"
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8081:80"

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    ports:
      - "8000:80"

